### ISSUE TITLE
Can't receive back data telemetry

### ISSUE THREAD

**Issue by max051505** [johnwalicki/Node-RED-Tello-Control#24]
Hello,
I try to redo your project with my drone DJI Tello. My computer uses Windows 10

-I have followed the explanations of the installation
-I imported the flow solution "Receiving Tello Telemetry Data".
-I opened port 8890 in the firewall
-I connected the computer to the Wi-Fi of the drone

I can launch the drone and make it move but I can't receive telemetry information.
This error is displayed in the debug and in the command prompt :
[udp in:bd7e5975.45fad8] error: EACCES

Do you know how to fix this error so that I can access the telemetry information?

![erreur](https://user-images.githubusercontent.com/79464453/108728047-76130900-7529-11eb-83c4-a3813f188979.png)

**Comment by johnwalicki** [comment]
Hi @max051505  - Its been a while since I played with my Tello.  Hopefully you're a winner from the IBM raffle?

I'm a Linux user so I'm not certain about Win10 firewall rules.  I show the Linux firewall commands to receive telemetry data in [Part5](https://github.com/johnwalicki/Node-RED-Tello-Control/blob/main/docs/PART5.md)

From your screenshot, you might have too many Node-RED flow tabs listening to port?  You might want to "Disable" all the flows except for the telemetry flow.  Double click on the tab and at the bottom there is a button to Enable / Disable. Change the other tabs to `Disabled` and Deploy.

**Comment by max051505** [comment]
Thank you for your answer ! 
I tried to do as you told me but it still doesn't work. So I decided to use ubuntu : 
- I installed Node-RED
- I imported your flow
- I opened the ports in the firewall (ufw)

But I've got a telemetry error again:
error] [udp in:bd7e5975.45fad8] error: EADDRINUSE

**Comment by max051505** [comment]
It's ok, I found the solution ! Thank you !

**Comment by johnwalicki** [comment]
Great news!

**Comment by VipinNa** [comment]
> It's ok, I found the solution ! Thank you !

Hi @max051505 

Could you share, what solution you got for the same on Windows 10?
I am facing the same problem

Vipin
